# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a6dfa033faa4c496a1cbc5925e3bdfc6f44ebb83f618ef65ba57775b702dbdd33f318b249bb302f791a281cbb3b9152d5d14c6368b799b8b6b160247f60ef0c3

test:
  secret_key_base: 280a95f67da90e2f3ddcfa504cc04b02ac7b635d9d4be810f6a3c0cdb08ff07e4bb7f00d3335c7f6d4fd9ae89f6d84359c30de2b45f8f005d8bbcec7ee60065a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
